accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
    address: cosmos1kdzkazludrnmnzchcxgs6znsjph5ugx4rhljrh
  - name: bob
    coins: ["10000token", "100000000stake"]
    address: cosmos1v0gfr46lp09e6m8m8qay04athst749sdf0jjpk
  - name: user1
    coins: ["10000token", "100000000stake"]
    address: cosmos1qekr6vpjhyn67ekt8gxc0p56ezt0f4fzmhuk6h
  - name: user2
    coins: ["10000token", "100000000stake"]
    address: cosmos106ljn6kds9vegaux0w4jnend97fdm50yec59vq
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
init:
  home: "~/.admin-module"
genesis:
  chain_id: "adminmodule"
  app_state:
    adminmodule:
      admins: ["cosmos1kdzkazludrnmnzchcxgs6znsjph5ugx4rhljrh", "cosmos1qekr6vpjhyn67ekt8gxc0p56ezt0f4fzmhuk6h", "cosmos106ljn6kds9vegaux0w4jnend97fdm50yec59vq"]
